sonar.projectKey=StudyPDF
sonar.projectName=StudyPDF
sonar.projectVersion=1.0.0

sonar.sources=.
sonar.exclusions=\
  .venv/**,\
  books/**,\
  data/**,\
  __pycache__/**,\
  **/__pycache__/**,\
  **/*.pyc

sonar.python.version=3.14
sonar.sourceEncoding=UTF-8
