sonar.projectKey=PedroAzin_studypdf
sonar.organization=pedroazin
sonar.projectName=StudyPDF
sonar.projectVersion=1.0.0

sonar.sources=studypdf,app.py,static
sonar.tests=tests
sonar.exclusions=\
  .venv/**,\
  books/**,\
  data/**,\
  docs/**,\
  templates/**,\
  __pycache__/**,\
  **/__pycache__/**,\
  **/*.pyc

sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=static/**
sonar.python.version=3.14
sonar.sourceEncoding=UTF-8
