import os
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent
STUDYPDF_DATABASE_URL = os.environ.get("STUDYPDF_DATABASE_URL", "").strip()
STUDYPDF_DATABASE_CONNECT_TIMEOUT_SECONDS = int(
    os.environ.get("STUDYPDF_DATABASE_CONNECT_TIMEOUT_SECONDS", "10").strip()
)
SUPABASE_URL = os.environ.get("SUPABASE_URL", "").strip().rstrip("/")
SUPABASE_SERVICE_ROLE_KEY = os.environ.get("SUPABASE_SERVICE_ROLE_KEY", "").strip()
STUDYPDF_STORAGE_BUCKET = os.environ.get("STUDYPDF_STORAGE_BUCKET", "studypdf").strip()
STUDYPDF_CRON_TOKEN = os.environ.get("STUDYPDF_CRON_TOKEN", "").strip()

ALLOWED_EXTENSIONS = {".pdf"}
NOTE_TYPES = {"DUVIDA", "DESTAQUE", "ANOTACAO", "TRABALHO", "REVISAR"}

MIN_IMAGE_WIDTH = 80
MIN_IMAGE_HEIGHT = 80
SOFT_HYPHENS = r"\-\u2010\u2011\u2012\u2013\u2014\u2015"

BOOK_STATUS_PROCESSING = "PROCESSING"
BOOK_STATUS_READY = "READY"
BOOK_STATUS_FAILED = "FAILED"

JOB_STATUS_PENDING = "PENDING"
JOB_STATUS_RUNNING = "RUNNING"
JOB_STATUS_DONE = "DONE"
JOB_STATUS_FAILED = "FAILED"
JOB_POLL_SECONDS = 3

FEATURE_UNDERSTANDING_CHECKS = os.environ.get("STUDYPDF_UNDERSTANDING_CHECKS", "").lower() in {
    "1",
    "true",
    "yes",
    "on",
}
