from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"
BOOKS_DIR = BASE_DIR / "books"
DB_PATH = DATA_DIR / "studypdf.sqlite3"

ALLOWED_EXTENSIONS = {".pdf"}
NOTE_TYPES = {"DUVIDA", "DESTAQUE", "ANOTACAO", "TRABALHO", "REVISAR"}

MIN_IMAGE_WIDTH = 80
MIN_IMAGE_HEIGHT = 80
SOFT_HYPHENS = r"\-\u2010\u2011\u2012\u2013\u2014\u2015"

BOOK_STATUS_PROCESSING = "PROCESSING"
BOOK_STATUS_READY = "READY"
BOOK_STATUS_FAILED = "FAILED"

JOB_STATUS_PENDING = "PENDING"
JOB_STATUS_RUNNING = "RUNNING"
JOB_STATUS_DONE = "DONE"
JOB_STATUS_FAILED = "FAILED"
JOB_POLL_SECONDS = 3
